#!/usr/bin/env bash
#    _
#   | |__  ___ _ ____      ___ __ ___
#   | '_ \/ __| '_ \ \ /\ / / '_  ` _ \  ^ cherry-noize
#   | |_) \__ \ |_) \ V  V /| | | | | |  ^ https://github.com/cherrynoize
#   |_.__/|___/ .__/ \_/\_/ |_| |_| |_|  ^ 0xo1m0x5w@mozmail.com
#             |_|

bspc config top_padding           "50"
bspc config bottom_padding        "0"
bspc config left_padding          "0"
bspc config right_padding         "0"
bspc config window_gap            "15"
bspc config border_width          "3"
bspc config focused_border_color  "#CA9A80"
#bspc config normal_border_color   "#3f2f1a"
#bspc config active_border_color   "#286c78"
bspc config presel_feedback_color "#2c3c4d"
