#!/usr/bin/env bash
#    _
#   | |__  ___ _ ____      ___ __ ___
#   | '_ \/ __| '_ \ \ /\ / / '_  ` _ \  ^ cherry-noize
#   | |_) \__ \ |_) \ V  V /| | | | | |  ^ https://github.com/cherrynoize
#   |_.__/|___/ .__/ \_/\_/ |_| |_| |_|  ^ 0xo1m0x5w@mozmail.com
#             |_|

. ../colorschemes/aero

bspc config top_padding           "50"
bspc config bottom_padding        "0"
bspc config left_padding          "0"
bspc config right_padding         "0"
bspc config window_gap            "15"
bspc config border_width          "3"
