#!/usr/bin/env bash
#  _
# | |__  ___ _ ____      ___ __ ___
# | '_ \/ __| '_ \ \ /\ / / '_  ` _ \ ^ cherrynoize
# | |_) \__ \ |_) \ V  V /| | | | | | ^ https://github.com/cherrynoize/dotfiles
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_| ^ cherrynoize@duck.com
#           |_|

vertical_padding=8
horizontal_padding=6

export top_padding="$vertical_padding"
export left_padding="$horizontal_padding"
export right_padding="$horizontal_padding"
export bottom_padding="$vertical_padding"
export useless_gaps="10"
export border_width="1"
