#!/usr/bin/env bash
#  _
# | |__  ___ _ ____      ___ __ ___
# | '_ \/ __| '_ \ \ /\ / / '_  ` _ \ ^ cherrynoize
# | |_) \__ \ |_) \ V  V /| | | | | | ^ https://github.com/cherrynoize/dotfiles
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_| ^ cherrynoize@duck.com
#           |_|

padding=10

export top_padding="$padding"
export left_padding="$padding"
export right_padding="$padding"
export bottom_padding="$padding"
export useless_gaps="25"
export border_width="0"
