#!/usr/bin/env bash
#    _
#   | |__  ___ _ ____      ___ __ ___
#   | '_ \/ __| '_ \ \ /\ / / '_  ` _ \  ^ cherry-noize
#   | |_) \__ \ |_) \ V  V /| | | | | |  ^ https://github.com/cherrynoize
#   |_.__/|___/ .__/ \_/\_/ |_| |_| |_|  ^ cherrynoize@duck.com
#             |_|
#

vertical_padding=10
horizontal_padding=8
bar_padding=40

bspc config top_padding           "$((vertical_padding + bar_padding))"
bspc config bottom_padding        "$vertical_padding"
bspc config left_padding          "$horizontal_padding"
bspc config right_padding         "$horizontal_padding"
bspc config window_gap            "15"
bspc config border_width          "3"
bspc config focused_border_color  "#c04334"
bspc config normal_border_color   "#842e24"
bspc config active_border_color   "#d4feff"
bspc config presel_feedback_color "#271927"
