#!/bin/bash
if [ "$(bluetooth status)" = "off" ]; then
  fg="#bfc9db"
  bg="transparent"
else
  fg="#0f0f17"
  bg="#bfc9db"
fi

case "$1" in
  fg)
    echo "$fg"
    ;;
  bg)
    echo "$bg"
    ;;
  *)
    bluetooth "$@"
    ;;
esac
