#!/bin/sh
if [ "$(light-shift status)" ]; then
  # light shift enabled
  fg="#0f0f17"
  bg="#bfc9db"
else
  # light shift disabled
  fg="#bfc9db"
  bg="transparent"
fi

case "$1" in
  fg)
    echo "$fg"
    ;;
  bg)
    echo "$bg"
    ;;
  *)
    light-shift "$@"
    ;;
esac
