#!/bin/bash
if [ "$(toggle-powersave -C)" = "powersave" ]; then
  icon=""
  title="powersave on"
  fg="#0f0f17"
  bg="#bfc9db"
else
  icon=""
  title="powersave off"
  fg="#ebddfb"
  bg="#F39E7D"
fi

case "$1" in
  icon)
    echo "$icon"
    ;;
  title)
    echo "$title"
    ;;
  fg)
    echo "$fg"
    ;;
  bg)
    echo "$bg"
    ;;
  *)
    toggle-powersave "$@"
    ;;
esac
