#!/bin/bash
case "$1" in
  bar|panel)
    panel_fg="#d78787"
    panel_bg="transparent"
    if [ "$(wireless)" = "enabled" ]; then
      bar_fg="#575268"
    elif [ "$(wireless)" = "inactive" ]; then
      bar_fg="#d78787"
    else
      bar_fg="#a1bdce"
      panel_fg="#bfc9db"
    fi

    case "$2" in
      fg|bg)
        v="$1_$2"
        echo "${!v}"
        exit
        ;;
      *)
        shift
        ;;
    esac
    ;;
esac
wireless "$@"
