#!/bin/sh

case "$(switch-mode -c)" in
  light)
    fg="#bfc9db"
    bg="transparent"
    ;;
  dark)
    fg="#0f0f17"
    bg="#bfc9db"
    ;;
  *)
    fg="#3f3f37"
    bg="#bfc9db"
    ;;
esac

case "$1" in
  fg)
    echo "$fg"
    ;;
  bg)
    echo "$bg"
    ;;
  *)
    night-mode "$@"
    ;;
esac
