custom_cmd="--custom-key-commands"
cmd_1_option="--cmd-brightness-up"
cmd_1="change-brightness up"
cmd_2_option="--cmd-brightness-down"
cmd_2="change-brightness down"
cmd_3_option="--cmd-audio-mute"
cmd_3="change-volume toggle"
cmd_4_option="--cmd-volume-up"
cmd_4="change-volume up"
cmd_5_option="--cmd-volume-down"
cmd_5="change-volume down"
cmd_6_option="--cmd-power-off"
cmd_6="power sleep"

pfp_padding="5"
