#!/usr/bin/env bash
#    _
#   | |__  ___ _ ____      ___ __ ___
#   | '_ \/ __| '_ \ \ /\ / / '_  ` _ \  ^ cherry-noize
#   | |_) \__ \ |_) \ V  V /| | | | | |  ^ https://github.com/cherrynoize
#   |_.__/|___/ .__/ \_/\_/ |_| |_| |_|  ^ 0xo1m0x5w@mozmail.com
#             |_|

#
# bspwm zombie theme
#

bspc config normal_border_color   "#292949"
bspc config active_border_color   "#286c78cc"
bspc config focused_border_color  "#492949"
bspc config presel_feedback_color "#286c78"
