#!/usr/bin/env bash
#    _
#   | |__  ___ _ ____      ___ __ ___
#   | '_ \/ __| '_ \ \ /\ / / '_  ` _ \  ^ cherry-noize
#   | |_) \__ \ |_) \ V  V /| | | | | |  ^ https://github.com/cherrynoize
#   |_.__/|___/ .__/ \_/\_/ |_| |_| |_|  ^ 0xo1m0x5w@mozmail.com
#             |_|

#
# bspwm zombie theme
#

bspc config top_padding           "55"
bspc config bottom_padding        "5"
bspc config left_padding          "5"
bspc config right_padding         "5"
bspc config window_gap            "10"
bspc config border_width          "5"
bspc config normal_border_color   "#2b3038"
bspc config active_border_color   "#286c7899"
bspc config focused_border_color  "#494949"
bspc config presel_feedback_color "#286c78"
