#!/usr/bin/env bash
#    _
#   | |__  ___ _ ____      ___ __ ___
#   | '_ \/ __| '_ \ \ /\ / / '_  ` _ \  ^ cherry-noize
#   | |_) \__ \ |_) \ V  V /| | | | | |  ^ https://github.com/cherrynoize
#   |_.__/|___/ .__/ \_/\_/ |_| |_| |_|  ^ cherrynoize@duck.com
#             |_|
#

#bspc config focused_border_color  "#FF6B81"
bspc config focused_border_color  "#FF8A9E"
bspc config normal_border_color   "#A97F6B"
bspc config active_border_color   "#da805e"
bspc config presel_feedback_color "#9c2c33"
