#!/usr/bin/env bash
#  _
# | |__  ___ _ ____      ___ __ ___
# | '_ \/ __| '_ \ \ /\ / / '_  ` _ \ ^ cherrynoize
# | |_) \__ \ |_) \ V  V /| | | | | | ^ https://github.com/cherrynoize/dotfiles
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_| ^ cherrynoize@duck.com
#           |_|

bspc config focused_border_color  "#6f70cb"
bspc config normal_border_color   "#4c4d8c"
bspc config active_border_color   "#e3e0ff"
bspc config presel_feedback_color "#12143c"
