#!/usr/bin/env bash
#  _
# | |__  ___ _ ____      ___ __ ___
# | '_ \/ __| '_ \ \ /\ / / '_  ` _ \ ^ cherrynoize
# | |_) \__ \ |_) \ V  V /| | | | | | ^ https://github.com/cherrynoize/dotfiles
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_| ^ cherrynoize@duck.com
#           |_|

bspc config focused_border_color  "#8e89cb"
bspc config normal_border_color   "#615e8c"
bspc config active_border_color   "#ffe8ff"
bspc config presel_feedback_color "#0f275f"
