#!/usr/bin/env bash
#  _
# | |__  ___ _ ____      ___ __ ___
# | '_ \/ __| '_ \ \ /\ / / '_  ` _ \ ^ cherrynoize
# | |_) \__ \ |_) \ V  V /| | | | | | ^ https://github.com/cherrynoize/dotfiles
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_| ^ cherrynoize@duck.com
#           |_|

bspc config focused_border_color  "#90709d"
bspc config normal_border_color   "#634d6c"
bspc config active_border_color   "#e2ffff"
bspc config presel_feedback_color "#122a4c"
