#!/usr/bin/env bash
#    _
#   | |__  ___ _ ____      ___ __ ___
#   | '_ \/ __| '_ \ \ /\ / / '_  ` _ \  ^ cherry-noize
#   | |_) \__ \ |_) \ V  V /| | | | | |  ^ https://github.com/cherrynoize
#   |_.__/|___/ .__/ \_/\_/ |_| |_| |_|  ^ cherrynoize@duck.com
#             |_|

#
# my bspwm default config 
#

# choose theme
theme="current"

# themes dir
themes_dir="$HOME/.config/bspwm/themes"

# bspwm config
bspc config split_ratio           0.5
bspc config single_monocle        true
bspc config gapless_monocle       false
bspc config focus_follows_pointer false
bspc config center_pseudo_tiled   true

bspc config pointer_modifier      mod4 
bspc config pointer_action1       move 
bspc config pointer_action2       resize_side 
bspc config pointer_action3       resize_corner

bspc config pointer_motion_interval     16

bspc config automatic_scheme      longest_side
bspc config initial_polarity      second_child

bspc config remove_disabled_monitors    true 
bspc config merge_overlapping_monitors  true

bspc config external_rules_command "$HOME/.config/bspwm/scripts/external_rules"

# run process if not already running
run() {
  if ! pgrep -f "$1" ;
  then
  "$@"&
  fi
}

# workspaces
workspaces() {
  name=1
  for monitor in $(bspc query -M); do
    # > 🌐 󱃫 󱌰 󱌬    󱀤   🎵󰲋  󰀘  󰢚 󰙯 󰻞󰭹 󰂫
    bspc monitor "${monitor}" -n "$name" -d ' ' ' ' ' ' ' ' ' ' ' ' '  ' ' ' '  ' ' ' ' '
    (( name++ ))
  done
}
workspaces

# source theme
. "${themes_dir}/${theme}"

# launch bar
switch-bar launch
# launch dunst
run dunst
# launch sxhkd
run sxhkd
 
xsetroot -cursor_name left_ptr
